
import { Language } from '../types';

export const translations = {
  en: {
    appTitle: "Chat with Experts",
    startNew: "Start New Topic",
    history: "History",
    settings: "Settings",
    language: "Language",
    inputPlaceholder: "Reply to the experts...",
    newTopicPlaceholder: "Start a new topic...",
    loadingExperts: "Scouring the globe for the best minds...",
    generatingDebate: "Experts are gathering their thoughts...",
    panelMembers: "Panel Members",
    disclaimer: "AI generated content. Please treat expert opinions with discretion.",
    welcomeTitle: "Throw an Idea",
    welcomeDesc: "Input any wild thought. AI will match 1-4 world-class experts for you and immediately start a deep roundtable discussion.",
    noHistory: "No discussions yet.",
    speakingStyle: "Speaking Style",
    save: "Save",
    cancel: "Cancel",
    dataManagement: "Data Management",
    clearHistory: "Clear All History",
    clearHistoryConfirm: "Are you sure? This will delete all chats on this device. This action cannot be undone.",
    clearSuccess: "All history cleared.",
    replaceExpert: "Swap Expert",
    devMode: "Developer Mode",
    enableDebugLog: "Enable Debug Logging",
    exportDebugData: "Export Debug Data (.json)",
    debugLogDesc: "Records API prompts and responses for evaluation. Stored locally.",
    suggestions: [
      { title: "Procrastination", question: "How to solve procrastination? From psychology perspectives." },
      { title: "Web 3.0", question: "Is Web 3.0 a pseudo-demand? What real problems does it solve?" },
      { title: "AI Replacement", question: "Will AI completely replace programmers?" },
      { title: "Immortality", question: "If humans achieved immortality, how would society collapse?" }
    ]
  },
  zh: {
    appTitle: "Chat with Experts",
    startNew: "开启新话题",
    history: "历史记录",
    settings: "设置",
    language: "语言",
    inputPlaceholder: "回应专家...",
    newTopicPlaceholder: "开启一个新的话题，例如：'为什么我们总是感到焦虑？'",
    loadingExperts: "正在全球范围内搜索最匹配的大脑...",
    generatingDebate: "专家已就位，正在整理思路...",
    panelMembers: "本轮受邀专家",
    disclaimer: "AI 生成内容仅供参考。请理性对待专家观点。",
    welcomeTitle: "抛出一个想法",
    welcomeDesc: "输入任何天马行空的念头，AI 将为你匹配 1-4 位世界级专家，即刻展开深度圆桌对谈。",
    noHistory: "暂无历史记录",
    speakingStyle: "说话风格",
    save: "保存",
    cancel: "取消",
    dataManagement: "数据管理",
    clearHistory: "清空所有记录",
    clearHistoryConfirm: "确定要清空吗？这将删除本机所有对话记录，且无法恢复。",
    clearSuccess: "记录已清空。",
    replaceExpert: "换一位",
    devMode: "开发者模式",
    enableDebugLog: "开启调试日志",
    exportDebugData: "导出调试数据 (.json)",
    debugLogDesc: "记录 API 请求参数与原始响应以供评测。仅本地存储。",
    suggestions: [
      { title: "拖延症解析", question: "从心理学和行为经济学角度，如何解决拖延症？" },
      { title: "Web 3.0 辩论", question: "Web 3.0 到底是不是伪需求？它解决了什么真实问题？" },
      { title: "职业危机", question: "随着 Copilot 的进化，AI 会完全取代程序员吗？" },
      { title: "思想实验", question: "如果人类实现了永生，社会结构会怎样崩塌？" }
    ]
  },
  es: {
    appTitle: "Chat with Experts",
    startNew: "Nuevo Tema",
    history: "Historial",
    settings: "Configuración",
    language: "Idioma",
    inputPlaceholder: "Responde a los expertos...",
    newTopicPlaceholder: "Inicia un nuevo tema...",
    loadingExperts: "Buscando las mejores mentes del mundo...",
    generatingDebate: "Los expertos están organizando sus ideas...",
    panelMembers: "Miembros del Panel",
    disclaimer: "Contenido generado por IA. Por favor, trata las opiniones con discreción.",
    welcomeTitle: "Lanza una Idea",
    welcomeDesc: "Introduce cualquier pensamiento. La IA encontrará 1-4 expertos de clase mundial para ti.",
    noHistory: "Sin discusiones aún.",
    speakingStyle: "Estilo",
    save: "Guardar",
    cancel: "Cancelar",
    dataManagement: "Gestión de Datos",
    clearHistory: "Borrar Historial",
    clearHistoryConfirm: "¿Estás seguro? Esto eliminará todos los chats en este dispositivo.",
    clearSuccess: "Historial borrado.",
    replaceExpert: "Cambiar Experto",
    devMode: "Modo Desarrollador",
    enableDebugLog: "Habilitar registro de depuración",
    exportDebugData: "Exportar datos de depuración",
    debugLogDesc: "Registra prompts y respuestas para evaluación. Almacenado localmente.",
    suggestions: [
      { title: "Procrastinación", question: "¿Cómo resolver la procrastinación desde la psicología?" },
      { title: "Web 3.0", question: "¿Es la Web 3.0 una pseudonecesidad?" },
      { title: "IA y Trabajo", question: "¿Reemplazará la IA completamente a los programadores?" },
      { title: "Inmortalidad", question: "Si los humanos lograran la inmortalidad, ¿cómo colapsaría la sociedad?" }
    ]
  },
  ja: {
    appTitle: "Chat with Experts",
    startNew: "新しいトピック",
    history: "履歴",
    settings: "設定",
    language: "言語",
    inputPlaceholder: "専門家に返信する...",
    newTopicPlaceholder: "新しいトピックを開始...",
    loadingExperts: "世界中の最高の頭脳を探しています...",
    generatingDebate: "専門家が考えをまとめています...",
    panelMembers: "パネルメンバー",
    disclaimer: "AI生成コンテンツです。専門家の意見は慎重に扱ってください。",
    welcomeTitle: "アイデアを投げる",
    welcomeDesc: "どんな突拍子もない考えでも入力してください。AIが1〜4人の世界クラスの専門家をマッチングします。",
    noHistory: "履歴はありません",
    speakingStyle: "話し方",
    save: "保存",
    cancel: "キャンセル",
    dataManagement: "データ管理",
    clearHistory: "履歴をすべて消去",
    clearHistoryConfirm: "本当によろしいですか？このデバイス上のすべてのチャットが削除されます。",
    clearSuccess: "履歴が消去されました。",
    replaceExpert: "メンバー交代",
    devMode: "開発者モード",
    enableDebugLog: "デバッグログを有効化",
    exportDebugData: "デバッグデータをエクスポート",
    debugLogDesc: "評価用にAPIリクエストとレスポンスを記録します。ローカルに保存されます。",
    suggestions: [
      { title: "先延ばし", question: "心理学の観点から先延ばしをどう解決するか？" },
      { title: "Web 3.0", question: "Web 3.0は疑似需要か？" },
      { title: "AI置換", question: "AIはプログラマーを完全に置き換えるか？" },
      { title: "不死", question: "人間が不死を実現したら、社会はどう崩壊するか？" }
    ]
  },
  fr: {
    appTitle: "Chat with Experts",
    startNew: "Nouveau Sujet",
    history: "Historique",
    settings: "Paramètres",
    language: "Langue",
    inputPlaceholder: "Répondre aux experts...",
    newTopicPlaceholder: "Lancer un nouveau sujet...",
    loadingExperts: "Recherche des meilleurs esprits à travers le monde...",
    generatingDebate: "Les experts rassemblent leurs pensées...",
    panelMembers: "Membres du Panel",
    disclaimer: "Contenu généré par IA. Traitez les opinions des experts avec discernement.",
    welcomeTitle: "Lancez une Idée",
    welcomeDesc: "Entrez n'importe quelle pensée. L'IA trouvera 1 à 4 experts de classe mondiale pour vous.",
    noHistory: "Pas encore de discussions.",
    speakingStyle: "Style",
    save: "Enregistrer",
    cancel: "Annuler",
    dataManagement: "Gestion des données",
    clearHistory: "Effacer l'historique",
    clearHistoryConfirm: "Êtes-vous sûr ? Cela supprimera tous les chats sur cet appareil.",
    clearSuccess: "Historique effacé.",
    replaceExpert: "Changer d'expert",
    devMode: "Mode Développeur",
    enableDebugLog: "Activer les logs de débogage",
    exportDebugData: "Exporter les données (.json)",
    debugLogDesc: "Enregistre les prompts et réponses pour évaluation. Stocké localement.",
    suggestions: [
      { title: "Procrastination", question: "Comment résoudre la procrastination ?" },
      { title: "Web 3.0", question: "Le Web 3.0 est-il une fausse demande ?" },
      { title: "Remplacement IA", question: "L'IA remplacera-t-elle complètement les programmeurs ?" },
      { title: "Immortalité", question: "Si les humains atteignaient l'immortalité, comment la société s'effondrerait-elle ?" }
    ]
  }
};

export const getTranslation = (lang: Language) => {
  return translations[lang] || translations.en;
};
